@startuml

actor Покупатель
actor Продавец
actor Админ

node Сервис {
    node "Эталоны"
    node "Товары"
}

package "Функции продавца" {
    (Создать товар)
    (Вручную определить эталон)
    (Авто определить эталон)
}

package "Функции админа" {
    (Создать эталон)
    (Авто определить товары)
}

package "Функции покупателя" {
    (Получить список всех товаров по эталону)
    (Получить инфо по товару)
}

Товары -up-> Эталоны

(Создать товар) -[hidden]down- (Вручную определить эталон)
(Вручную определить эталон) -[hidden]down- (Авто определить эталон)

Продавец -right-> (Создать товар)
Продавец -right-> (Вручную определить эталон)
Продавец -right-> (Авто определить эталон)

(Создать товар) -right-> Товары
(Вручную определить эталон) -right-> Товары
(Авто определить эталон) -right-> Товары

(Создать эталон) -[hidden]down- (Авто определить товары)

Админ -left-> (Создать эталон)
Админ -left-> (Авто определить товары)

(Создать эталон) -left-> Эталоны
(Авто определить товары) -left-> Товары

(Получить список всех товаров по эталону) -[hidden]left- (Получить инфо по товару)

Покупатель -up-> (Получить список всех товаров по эталону)
Покупатель -up-> (Получить инфо по товару)

(Получить список всех товаров по эталону) -up-> Товары
(Получить инфо по товару) -up-> Товары

@enduml
